### ISSUE TITLE
Unable to wrap text in JavaFX

### ISSUE THREAD

**Issue by leawang0** [nus-cs2103-AY2324S1/forum#125]
Hi I am trying to style my GUI to make it look better. I referred to the code written by @shishirbychapur (Thank you so much and I credited you in my code). However, after I created a chat bubble for containing the text message, I am unable to wrap the text. Previously, I was able to wrap my text with the most basic GUI.

The `Label `that contained my message already has `wrapText = "true"` and I feel that probably something else is interfering with it. 
However, I cannot find out exactly where is the problem. 😢

This is what it looks like now: 
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/83194176/2fa9df13-ac8e-4062-bb74-dc9b7e2adf37)

`DialogBox.fxml`:
```fxml
<fx:root alignment="TOP_RIGHT" maxHeight="Infinity" maxWidth="1.7976931348623157E308" prefWidth="400.0"
         type="javafx.scene.layout.HBox" xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1">
    <children>
        <FlowPane fx:id="messageOutline" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity"
                  prefHeight="39.0" prefWidth="400.0" prefWrapLength="380" styleClass="gray-background"
                  stylesheets="@../css/Application.css" >
            <children>
                <Label fx:id="dialog" text="Label with long text that should wrap to the next line when needed."
                       wrapText="true">
                <opaqueInsets>
                    <Insets />
                </opaqueInsets>
                <font>
                    <Font name="Segoe UI" size="14.0" />
                </font>
                <padding>
                    <Insets bottom="15.0" left="12.0" right="20.0" top="12.0" />
                </padding>
                </Label>
            </children>
            <HBox.margin>
                <Insets />
            </HBox.margin>
        </FlowPane>
        <Circle fx:id="circle" fill="#007df2" radius="23.0" stroke="BLACK" strokeType="INSIDE" strokeWidth="0.0">
            <HBox.margin>
                <Insets left="10.0" right="10.0" />
            </HBox.margin>
        </Circle>
    </children>
    <padding>
        <Insets bottom="15.0" left="10.0" right="10.0" top="15.0" />
    </padding>
</fx:root>
```
DialogBox.java
```fxml
private DialogBox(String text, Image img, boolean isUser) {
       // ...
        dialog.setText(text);
        dialog.setWrapText(true);
        circle.setFill(new ImagePattern(img));
        messageOutline.setPrefWidth(280);
        messageOutline.prefHeightProperty().bind(dialog.heightProperty());
        messageOutline.getStyleClass().clear();
        if (isUser) {
            messageOutline.getStyleClass().add("blue-background");
        } else {
            messageOutline.getStyleClass().add("lavender-background");
        }
    }
```
relevant css blocks:
```css
.text-area {
    -fx-border-color: #f6f7f2;
    -fx-border-radius: 20;
    -fx-focus-color: transparent;
    -fx-faint-focus-color: transparent;
    -fx-text-box-border: transparent;
    -fx-background-color: beige;
}

.message-text {
    -fx-border-radius: 20;
    -fx-background-color: #ffffff;
    -fx-border-color: "#f6f7f2";
}
```
